language: scala
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-$CI_VERSION.tar.gz | tar xz
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
- cp /etc/sbt/sbtopts .sbtopts; echo "-Dsbt.global.base=$TRAVIS_BUILD_DIR/ci" >> .sbtopts
script:
- sbt test package
  && ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
  && ci/sbt-ci-build-doc.sh https://commbank.github.io/ https://github.com/CommBank/answer/
  && if git rev-parse --verify refs/heads/gh-pages 2>&/dev/null; then ci/ci-push-branch.sh gh-pages; fi
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    - https://webhooks.gitter.im/e/a803046bf00a8b62a326
    on_success: always
    on_failure: always
    on_start: never
env:
  global:
  - CI_VERSION=3.2.2-20160718231250-50a210b
  - secure: Fx3t0GnbRfIjpEabacr8d6O0qwnEl4DrD5BAVBiLpNbqvvNfhr9ptux452Kx54I7IxjlEAG4QJ3WEGyA8yw+7svPKkSAX1zzahLm7GSVXA/Mufg7cBRWZNPTEBXBfgLrcQuBtQ25qXtUPLf6V0D7G+uE7NCkbdHL+YIYNNC4vaM=
  - secure: sAvnGTHoWzsVYhNZD3Ih/Il2Y/TYlKGwbLi/9PxqybbU/18sFPFofcHS2plrv7EDOkNyUd64ruiUHRlBQ5FW3z2zEawsyXTQrsy0y0D5dfRcpXrsromLzF/2uILaS9+ozUxNKW9mi+lyNhZgU6kKrkpPcNQ3YpiDZN/NVlzI8qI=
before_install:
- openssl aes-256-cbc -K $encrypted_08f5a660006a_key -iv $encrypted_08f5a660006a_iv
  -in .ci/deploy-key.enc -out .ci/deploy-key.pem -d
